#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar dunst)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &

dunst &
hyprpaper --config ~/.config/hypr/hyprpapr.conf &
Exec=env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify --uri=%U &
#kitty tty-clock &
