#!/bin/bash

# Kill already running process
_ps=(waybar dunst)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

openrazer-daemon &

# Lauch statusbar (waybar)
WAYBAR_CFG=$HOME/.config/hypr/waybar/
waybar -c "$WAYBAR_CFG"/config.jsonc -s "$WAYBAR_CFG"/style.css & disown

# generate an ~/.Xauthority file if there is none
xauth_file=$(xauth -q info | grep "Xauthority" |awk -F ":" '{print$2}' | tr -d ' ')
if [ ! -f "$xauth_file" ]; then
  xauth gen "$DISPLAY" &> /dev/null
fi

nm-applet &
dunst &
hyprpaper --config ~/.config/hypr/hyprpapr.conf &
sleep 8 && spotify &
sleep 8 && webcord &
